#Dockerfile
FROM nvcr.io/nvidia/pytorch:25.06-py3

RUN pip install scikit-image && \
    pip install matplotlib && \
    pip install lpips && \
    pip install kornia && \
    pip install cdsapi && \
    pip install dask && \
    pip install pytorch-lightning && \
    pip install scikit-learn && \
    pip install netcdf4 && \
    pip install wandb && \
    pip install xarray && \
    pip install tensorboard && \
    pip install timm && \
    pip install "opencv-python-headless<4.10"


